apiVersion: v1
kind: PersistentVolume
metadata:	
   name: my-pv2
   labels: 
      volume: test
spec: 
   storageClassName: local 
   accessModes: 
        - ReadWriteMany
   capacity: 
        storage: 2Gi
   hostPath: 
        path: "/home/ubuntu"
