apiVersion: v1
kind: Pod
metadata:
   name: init-container
   labels: 
      app: init-app
spec:
    containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: workdir
    initContainers:
         - name: busybox
           image: busybox
           command: ["/bin/sh"]    
           args: ["-c","echo '<html><h1>This is init container </h1></html>' >> /work-dir/index.html"]
           volumeMounts:
             - mountPath: "/work-dir"
               name: workdir
    volumes:
       - name: workdir
         emptyDir: {}
