apiVersion: v1
kind: Pod
metadata:
    name: liveness-probe-tcp
spec:
    containers:
       - name: liveness
         image: registry.k8s.io/liveness
         args:
          - /server
         livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 2
