apiVersion: v1
kind: Pod
metadata:
    name: nginx-configmaps 
spec:
    containers: 
       - name: nginx
         image: nginx:1.14.2
         ports:
            - containerPort: 80
         env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                 name: my-config-2
                 key: environment
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                 name: my-config-2
                 key: db_url
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: my-secret
                 key: db_password
